<?php
session_name("ADMIN_SESSION");
session_start();
require('../FPDF/fpdf.php');
require '../connection.php';
include('Check_token.php');

class PDF extends FPDF
{
    public $widths;
    public $aligns;
    public $headers;

    function Header()
    {
        $pageWidth = $this->GetPageWidth();
        $logoWidth = 22;
        $logoHeight = 22;
        $logoY = 6;
        $textBlockWidth = 100;
        $spaceBetween = -2;

        // Total width of logos + text block
        $totalWidth = $logoWidth + $spaceBetween + $textBlockWidth + $spaceBetween + $logoWidth;
        $startX = ($pageWidth - $totalWidth) / 2;

        // Left Logo
        $this->Image('../Images/ptpl-logo.png', $startX, $logoY, $logoWidth, $logoHeight);

        // Text Block
        $textStartX = $startX + $logoWidth + $spaceBetween;
        $textStartY = $logoY + 6;

        $this->SetXY($textStartX, $textStartY);
        $this->SetFont('Arial', 'B', 15);
        $this->Cell($textBlockWidth, 6, 'PTPL - Corporate Inventory Report', 0, 2, 'C');

        $this->SetFont('Arial', 'I', 10);
        $this->Cell($textBlockWidth, 5, 'Inventory & Asset Management | Lahore, Gulberg III', 0, 2, 'C');

        // Right Logo
        $rightLogoX = $textStartX + $textBlockWidth + $spaceBetween;
        $this->Image('../Images/ptpl-logo11.png', $rightLogoX, 9, 20, 18);

        // Divider Line
        $this->SetY($logoY + $logoHeight + 2);
        $this->SetDrawColor(180);
        $this->SetLineWidth(0.1);
        $this->Line($startX, $this->GetY(), $startX + $totalWidth, $this->GetY());

        $this->Ln(8);

        // Report Info
        $this->SetFont('Arial', 'B', 12);
        $this->Cell(10, 5, '', 0, 0);
        $this->Cell(80, 5, 'Organization Information', 0, 0);
        $this->Cell(80, 5, '', 0, 0);
        $this->Cell(80,  5, 'Report Summary', 0, 1);
        $this->Ln(3);

        global $category, $currentDate;

        $this->SetFont('Arial', '', 10);
        $this->Cell(10, 5, '', 0, 0);
        $this->Cell(160, 5, 'Company: Punjab Thermal Power Limited', 0, 0);
        $this->Cell(25, 5, 'Category:', 0, 0);
        $this->Cell(34, 5, (!empty($category) ? $category : 'All Categories'), 0, 1);

        $this->Cell(10, 5, '', 0, 0);
        $this->Cell(160, 5, 'Head Office: GF 7/C-1, Gulberg III, Lahore, Pakistan', 0, 0);
        $this->Cell(25, 5, 'Invoice Date:', 0, 0);
        $this->Cell(34, 5, $currentDate, 0, 1);

        $this->Cell(10, 5, '', 0, 0);
        $this->Cell(160, 5, 'Email: info@ptpl.pk', 0, 1);

        $this->Ln(8);
    }


    function Footer()
    {
        $this->SetY(-15);

        // Background
        $this->SetFillColor(30, 60, 120);
        $this->SetTextColor(255, 255, 255);
        $this->SetDrawColor(255, 255, 255);
        $this->SetFont('Arial', 'I', 10);

        // Footer content
        $this->Cell(0, 10, 'Generated by STOCKSYNC - Inventory & File Management Sys.', 1, 0, 'C', true);

        // Page number on right
        $this->SetXY(-40, -15);
        $this->Cell(35, 10, 'Page ' . $this->PageNo() . ' of {nb}', 1, 0, 'R', true);
    }

    function FancyRow($data, $widths, $aligns)
    {
        $nb = 0;
        for ($i = 0; $i < count($data); $i++) {
            $nb = max($nb, $this->NbLines($widths[$i], $data[$i]));
        }
        $lineHeight = 9;
        $h = $lineHeight * $nb;
        $this->CheckPageBreak($h);

        for ($i = 0; $i < count($data); $i++) {
            $w = $widths[$i];
            $a = isset($aligns[$i]) ? $aligns[$i] : 'L';
            $x = $this->GetX();
            $y = $this->GetY();
            $this->Rect($x, $y, $w, $h);
            $this->MultiCell($w, $lineHeight, $data[$i], 0, $a);
            $this->SetXY($x + $w, $y);
        }
        $this->Ln($h);
    }


    function CheckPageBreak($h)
    {
        // Add buffer of 10 units above footer
        $bottomMarginBuffer = 10;

        if ($this->GetY() + $h + $bottomMarginBuffer > $this->PageBreakTrigger) {
            $this->AddPage($this->CurOrientation);

            // Re-add table headers
            $this->SetFont('Arial', 'B', 10);
            $this->SetFillColor(230, 230, 230);
            $this->FancyRow($this->headers, $this->widths, $this->aligns);

            // Reset font back to normal for data rows
            $this->SetFont('Arial', '', 9);
        }
    }



    function NbLines($w, $txt)
    {
        $cw = &$this->CurrentFont['cw'];
        if ($w == 0) $w = $this->w - $this->rMargin - $this->x;
        $wmax = ($w - 2 * $this->cMargin) * 1000 / $this->FontSize;
        $s = str_replace("\r", '', $txt);
        $nb = strlen($s);
        if ($nb > 0 && $s[$nb - 1] == "\n") $nb--;
        $sep = -1;
        $i = 0;
        $j = 0;
        $l = 0;
        $nl = 1;
        while ($i < $nb) {
            $c = $s[$i];
            if ($c == "\n") {
                $i++;
                $sep = -1;
                $j = $i;
                $l = 0;
                $nl++;
                continue;
            }
            if ($c == ' ') $sep = $i;
            $l += $cw[$c];
            if ($l > $wmax) {
                if ($sep == -1) {
                    if ($i == $j) $i++;
                } else {
                    $i = $sep + 1;
                }
                $sep = -1;
                $j = $i;
                $l = 0;
                $nl++;
            } else {
                $i++;
            }
        }
        return $nl;
    }
}

// === Data Fetching ===
$category = $_GET['category'] ?? '';
$processor = $_GET['processor'] ?? '';
$person_name = $_GET['person_name'] ?? '';
$currentDate = date('d, M Y');

$sql = "SELECT * FROM laptops WHERE 1";
if (!empty($category)) {
    $sql .= " AND category = '" . mysqli_real_escape_string($con, $category) . "'";
}
if (!empty($processor)) {
    $sql .= " AND processor = '" . mysqli_real_escape_string($con, $processor) . "'";
}
if (!empty($person_name)) {
    $sql .= " AND person_name = '" . mysqli_real_escape_string($con, $person_name) . "'";
}
$result = $con->query($sql);

$pdf = new PDF();
$pdf->AliasNbPages();
$pdf->AddPage('L');

$headers = ['S-N', 'Brand', 'Model', 'Processor', 'Serial No.', 'Delivery Date', 'Age', 'Designation', 'Person', 'Status', 'Price', 'Qty', 'Total'];
$widths = [10, 28, 22, 21, 28, 25, 18, 25, 30, 21, 18, 15, 21];
$aligns = array_fill(0, count($headers), 'C');

$pdf->headers = $headers;
$pdf->widths = $widths;
$pdf->aligns = $aligns;

$pdf->SetFont('Arial', 'B', 10);
$pdf->SetFillColor(180, 180, 180);
$title = (!empty($category) && !empty($processor))
    ? ucfirst($processor) . " " . ucfirst($category) . " Product Inventory (2017 To 2025)"
    : 'Overall Inventory (2016 To 2025)';
$pdf->Cell(280, 10, $title, 0, 1, 'C', true);

// Table Header
$pdf->SetFont('Arial', 'B', 10);
$pdf->SetFillColor(230, 230, 230);
$pdf->FancyRow($headers, $widths, $aligns);

// Table Data
$pdf->SetFont('Arial', '', 9);
$dataRows = [];
$totalSum = 0;
$Sr = 1;

while ($row = $result->fetch_assoc()) {
    $total = $row['price'] * $row['quantity'];
    $totalSum += $total;

    $dataRows[] = [
        $Sr++,
        $row['brand'],
        $row['model'],
        $row['processor'],
        $row['serialNumber'],
        $row['delivery_date'],
        $row['total_age'],
        $row['designation'],
        $row['person_name'],
        $row['status'],
        number_format($row['price']),
        $row['quantity'],
        number_format($total)
    ];
}

$rowHeight = 9;
$subtotalHeight = 10;
$dataCount = count($dataRows);

for ($i = 0; $i < $dataCount; $i++) {
    // If it's the last row, calculate space required for row + subtotal
    if ($i === $dataCount - 1) {
        // Subtotal formatting and width adjustment
        $formattedSubtotal = number_format($totalSum);
        $subtotalLabel = 'Sub Total:';

        $subtotalValueWidth = $pdf->GetStringWidth($formattedSubtotal) + 6;
        $minWidth = 20;
        $maxWidth = 40;
        $valueCellWidth = max($minWidth, min($subtotalValueWidth, $maxWidth));

        $labelCellWidth = array_sum($widths) - $valueCellWidth;

        $spaceNeeded = $rowHeight + $subtotalHeight + 5;
        $spaceLeft = $pdf->GetPageHeight() - $pdf->GetY() - 20;

        if ($spaceNeeded > $spaceLeft) {
            $pdf->AddPage('L');
            $pdf->SetFont('Arial', 'B', 10);
            $pdf->SetFillColor(230, 230, 230);
            $pdf->FancyRow($headers, $widths, $aligns);
            $pdf->SetFont('Arial', '', 9);
        }
    }

    $pdf->FancyRow($dataRows[$i], $widths, $aligns);
}

// Print dynamic-width subtotal row
$pdf->SetFont('Arial', 'B', 10);
$pdf->Cell($labelCellWidth, $subtotalHeight, $subtotalLabel, 0, 0, 'R');
$pdf->Cell($valueCellWidth, $subtotalHeight, $formattedSubtotal, 1, 1, 'C');


header("Content-type: application/pdf");
$pdf->Output();
